### ISSUE TITLE
Protractor 4.0.0 Compatibility

### ISSUE THREAD

**Issue by tjsail33** [applitools/Eyes.Protractor#11]
Eyes is currently failing using Protractor 4.0.0. It would be great if the library could be updated for compatibility.

**Comment by marthinus-engelbrecht** [comment]
👍

**Comment by danielputerman** [comment]
Hi, thanks for notifying us. We're working on it, hopefully have an update very soon.

**Comment by danielputerman** [comment]
Fixed in commit ffceed897c7acfab8e131871b3556689353b33cf , and is available newest version in npm: eyes.protractor ver. 0.0.54 .

**Comment by marthinus-engelbrecht** [comment]
👍 Will give it a try tomorrow
