### ISSUE TITLE
User triggers via 'actions' are not recorded for playback

### ISSUE THREAD

**Issue by zavelevsky** [applitools/Eyes.Protractor#4]
User triggers are recorded and shown in the console when done via 'element.click' or 'element.sendKeys'.

However - this example of a way to click a button would not be recorded and played:

```javascript
browser.actions().mouseMove(element(by.id('gobutton'))).perform();
browser.actions().click(protractor.Button.LEFT).perform();
```

browser.actions() should be wrapped. It's basically a selenium-webdriver functionality.

**Comment by danielputerman** [comment]
Abandoned issue.
