### ISSUE TITLE
Eyes always crashes when it's disabled

### ISSUE THREAD

**Issue by sJhonny-e** [applitools/Eyes.Protractor#5]
happened to me on the latest npm version (0.0.26); I set eyes to be disabled, and ran 'checkWindow'.
however, Eyes.protractor always checks the result from base.checkWindow:

https://github.com/applitools/Eyes.Protractor/blob/master/src/Eyes.js#L125

but if eyes is disabled, "resolve" is called without parameters: https://github.com/applitools/Eyes.Sdk.JavaScript/blob/master/src/EyesBase.js#L511
, which causes the caller to crash.

**Comment by zavelevsky** [comment]
fixed. Now checking whether the SDK is disabled and avoiding unnecessary actions and overriding of globals. commie cbf4b4c03e56dfb4567becb6d12fe58ecc0ab0b4
