### ISSUE TITLE
Compatibility with protractor 1.5.0

### ISSUE THREAD

**Issue by alecxe** [applitools/Eyes.Protractor#6]
The example provided in the `README.md` is not working with the currently latest protractor 1.5.0, getting:

    TypeError: Object #<Object> has no method 'getInstance'

This is because of the [breaking change in `protractor`](https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes):

> protractor.getInstance() had been unused (replaced by global browser in v0.12.0) and is now removed.

Please update the example provided in the `README`. Thanks.

**Comment by zavelevsky** [comment]
Thanks for the heads-up - will go through the example and make the necessary changes promptly.

**Comment by zavelevsky** [comment]
updated the example in the README file as suggested - thank you very much.
c484f65ec3377315e971c7f2a289749031806be1
