### ISSUE TITLE
timeout: timed out after 30000 msec waiting for spec to complete

### ISSUE THREAD

**Issue by dfguo** [applitools/Eyes.Protractor#7]
turning eyes.setForceFullPageScreenshot(true) on always result in this timeout

**Comment by zavelevsky** [comment]
Are you running the tests locally or remotely? You might need to increase the timeouts.
Please consider the flow of visual validation checkpoint:
 1. To take a screenshot - we ask the driver for a screenshot. This is not a short operation - and if the driver runs remotely then fetching this screenshot over the network takes time too.
  * In case of a full page screenshot we actually have to take multiple screenshots and scroll the page between them - more time (take screenshot, send JS command, repeat). Full page screenshot is not supported by most browsers so we have to do it this way.
 2. After the screenshot is ready (full page screenshot stitched from its pieces) - it is upload for inspection in Applitools Eyes server.

So, as you can see, adding visual validation increases the run time of the tests. The overhead increases with remote runs and full page screenshots - so the timeout settings should be increased accordingly.

**Comment by dfguo** [comment]
I'm running the tests locally. Does the 30s include uploading to Applitools server?

**Comment by zavelevsky** [comment]
I believe the timeout you get is from Jasmine - and it's the timeout for the completion of an "it" block. So yes - it includes the upload time as you need the analysis response in order to determine the test success/failure.

**Comment by danielputerman** [comment]
@dfguo Did setting Jasmin timeout solved the issue?
